#!/bin/bash

echo -n "what is the admin password: " && read password
export password

CRUMB=$(curl -s "http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)" --user "admin:$password")

curl -s -XPOST 'http://localhost:8080/createItem?name=job1' -u admin:$password --data-binary @job1.xml -H "Content-Type:text/xml"

curl -s -XPOST 'http://localhost:8080/createItem?name=job2' -u admin:$password --data-binary @job2.xml -H "Content-Type:text/xml"
